ALTER TABLE "vendors" ADD COLUMN IF NOT EXISTS "deliveryPhone" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "riderNotifiedAt" TIMESTAMP(3);
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "riderNotifyNote" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "riderAckAt" TIMESTAMP(3);
