ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "pickedUpAt" TIMESTAMP(3);
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "deliveredAt" TIMESTAMP(3);
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "delayReason" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "delayProof" TEXT;
